### ISSUE TITLE
Graphical editor SWTBot tests failing

### ISSUE THREAD

**Issue by lwrage** [osate/osate2#2018]
## Summary

Some tests fail after the upgrade to Eclipse 2019-09. This happens on Linux, macOS, and Windows.

I have disabled the tests for now.

## Environment

* **OSATE Version**: nightly
* **Operating System**: all

**Comment by philip-alldredge** [comment]
Do you know if it is a problem with the tests or a problem with the graphical editor?

**Comment by lwrage** [comment]
There seems to be a timeout in recognizing that the "new project" dialog has opened.

**Comment by philip-alldredge** [comment]
Do you have a log of that. I tried to take a quick look and I'm unable to reproduce that issue.

I am getting a legitimate test failure. Appears to be caused by something outside the GE. I'll add another comment with details when I have them.

**Comment by philip-alldredge** [comment]
Okay. I am unable to reproduce the "New Project" dialog issue. A log would be helpful.

I am consistently getting an error when trying to rename connections. It is unclear what is causing it but it appears to be a problem with the test and not the GE. Will prioritize once development restarts.

**Comment by lwrage** [comment]
I get the timeout when I run the GE tests inside eclipse: right click on the ge test project, run as -> junit plug-in test. Initially it also complained that I wasn't running the osate2 product but I updated that in the run configuration. Two tests hang with an open "new" dialog. It looks like a problem with the test.

**Comment by lwrage** [comment]
There was another more pressing build issue. I'll provide more detail once the jenkins builds are back to normal.

**Comment by philip-alldredge** [comment]
Your issue is caused by "Run in UI thread" being checked. I usually launch the tests using a SWTBot Test configuration rather than a JUnit Plug-in Test configuration so I"m not sure if there are any other pitfalls in doing it that way.

We won't be able to take a deep look until we resume work so no rush. I just took a quick look to check if it was something that would prevent usage of the editor. The issue that I'm seeing appears to be with the test.

**Comment by philip-alldredge** [comment]
I'm hoping it is the same one that makes it fail on my system. At least then it would be consistent.

**Comment by lwrage** [comment]
From the build log:
```
testGraphicalEditor(org.osate.ge.tests.endToEnd.PrimaryEndToEndTest)  Time elapsed: 64.414 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu item matching: with mnemonic 'Rename...'
	at org.osate.ge.tests.endToEnd.PrimaryEndToEndTest.createHardwareProject(PrimaryEndToEndTest.java:268)
	at org.osate.ge.tests.endToEnd.PrimaryEndToEndTest.testGraphicalEditor(PrimaryEndToEndTest.java:35)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find menu item matching: with mnemonic 'Rename...'
	at org.osate.ge.tests.endToEnd.PrimaryEndToEndTest.createHardwareProject(PrimaryEndToEndTest.java:268)
	at org.osate.ge.tests.endToEnd.PrimaryEndToEndTest.testGraphicalEditor(PrimaryEndToEndTest.java:35)
```
Running as swtbot test I get the same exception:
```
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu item matching: with mnemonic 'Rename...'
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:474)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntilWidgetAppears(SWTBot.java:1)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotRootMenu.menu(SWTBotRootMenu.java:126)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotRootMenu.menu(SWTBotRootMenu.java:110)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotRootMenu.menu(SWTBotRootMenu.java:89)
	at org.osate.ge.tests.endToEnd.util.UiTestUtil.clickContextMenuOfOutlineViewItem(UiTestUtil.java:499)
	at org.osate.ge.tests.endToEnd.util.OsateGeTestCommands.renameElementFromOutlineView(OsateGeTestCommands.java:505)
	at org.osate.ge.tests.endToEnd.util.OsateGeTestCommands.createConnectionAndLayout(OsateGeTestCommands.java:388)
	at org.osate.ge.tests.endToEnd.PrimaryEndToEndTest.createHardwareProject(PrimaryEndToEndTest.java:268)
	at org.osate.ge.tests.endToEnd.PrimaryEndToEndTest.testGraphicalEditor(PrimaryEndToEndTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.swtbot.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:64)
	at org.eclipse.swtbot.eclipse.core.UITestApplication.runTests(UITestApplication.java:120)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:76)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find menu item matching: with mnemonic 'Rename...'
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:524)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:498)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:486)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:468)
	... 35 more
```

**Comment by philip-alldredge** [comment]
Thanks. That is the same error I'm receiving so at least it is reproducible.

**Comment by philip-alldredge** [comment]
@lwrage do you mind running the tests again locally and on the build server with the current master? I am no longer able to reproduce it. I'm wondering if this is somehow related to the context menu issues that were affecting the xtext outline as well.

**Comment by lwrage** [comment]
Given that the failures occurred in the outline view context menu I'd say you're right. Tests run ok on my laptop.

**Comment by philip-alldredge** [comment]
How do you feel about re-enabling the tests? Does this need to remain open?

**Comment by lwrage** [comment]
I expect them to work. Could you create a PR that enables them?

**Comment by philip-alldredge** [comment]
Done

**Comment by lwrage** [comment]
Done in 54c8d126aa8dd64ca5c948e341a87fa81b213f11
