### ISSUE TITLE
NullPointerException in Check Unhandled Faults

### ISSUE THREAD

**Issue by brlarson** [osate/osate2#2092]
## Summary
Running Check Unhandled Faults causes a NullPointerException
## Expected and Current Behavior
Expected:  generate .csv file in UnhandledFaults folder

Current:
```
java.lang.NullPointerException
	at org.osate.aadl2.modelsupport.errorreporting.AnalysisErrorReporterManager.error(AnalysisErrorReporterManager.java:249)
	at org.osate.ui.handlers.AbstractAaxlHandler.error(AbstractAaxlHandler.java:604)
	at org.osate.aadl2.errormodel.analysis.handlers.UnhandledFaultsHandler.checkPropagationPathErrorTypes(UnhandledFaultsHandler.java:98)
	at org.osate.aadl2.errormodel.analysis.handlers.UnhandledFaultsHandler.doAaxlAction(UnhandledFaultsHandler.java:78)
	at org.osate.ui.handlers.AbstractAaxlHandler.processAaxlAction(AbstractAaxlHandler.java:482)
	at org.osate.ui.handlers.AbstractAaxlHandler.actionBody(AbstractAaxlHandler.java:191)
	at org.osate.ui.handlers.AaxlReadOnlyHandlerAsJob$ActionAsJob.runInWorkspace(AaxlReadOnlyHandlerAsJob.java:124)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

## Steps to Reproduce

I'd need to upload, or emai:
liPCA_Context_Open_PCA_Context_i_Instance.aaxl2 

Only saw the stack trace because I'm running from sources from the master branch, pulled 12/1/2019.

Before I made significant model changes, Unhandled Faults ran fine.
## Environment
I tried it with downloaded 2.6.0 too, and there was no .csv output, either.  (Can only see stack trace when running from sources.
* **OSATE Version**: 2.6.0.vfinal 
* **Operating System**:  MacOS 10.14.6

**Comment by lwrage** [comment]
Waiting for AADL model.

**Comment by brlarson** [comment]
Let me know if you want the whole model.

On Dec 2, 2019, at 1:36 PM, Lutz Wrage <notifications@github.com<mailto:notifications@github.com>> wrote:


Waiting for AADL model.

**Comment by lwrage** [comment]
The whole model, please. With instructions which component to instantiate, where to find that component, how to run the analysis, etc.

**Comment by brlarson** [comment]
Functional_PCA->packages->iPCA_Context.aadl

Instantiate iPCA_Context::Open_PCA_Context.i


On Dec 3, 2019, at 11:56 AM, Lutz Wrage <notifications@github.com<mailto:notifications@github.com>> wrote:


The whole model, please. With instructions which component to instantiate, where to find that component, how to run the analysis, etc.

**Comment by lwrage** [comment]
Did you forget to send the model?
