### ISSUE TITLE
FHA: IndexOutOfBoundsException if likelihood unspecified

### ISSUE THREAD

**Issue by jjhugues** [osate/osate2#2093]
The following example triggers an exception

```
package foo
public
	system bar
		annex emv2 {**
			use behavior ErrorLibrary::FailStop; -- definition of error modes
			
			properties
				EMV2::severity => 1 applies to Failstop;
					--		EMV2::likelihood => C applies to Failstop;
				EMV2::hazards => ([crossreference => "";
						failure => "failure";
						phases => ("phases");
						description => "descr.";
						comment => "comment";
					]) applies to Failstop;
		**};
	end bar;

	system implementation bar.i
	end bar.i;
end foo;
```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at org.osate.aadl2.errormodel.analysis.fha.FHAReport.reportHazardProperty(FHAReport.java:303)
	at org.osate.aadl2.errormodel.analysis.fha.FHAReport.processHazards(FHAReport.java:138)
	at org.osate.aadl2.errormodel.analysis.fha.FHAReport.doFHAReport(FHAReport.java:98)
	at org.osate.aadl2.errormodel.analysis.handlers.FHAHandler.doAaxlAction(FHAHandler.java:70)
	at org.osate.ui.handlers.AbstractAaxlHandler.processAaxlAction(AbstractAaxlHandler.java:482)
	at org.osate.ui.handlers.AbstractAaxlHandler.actionBody(AbstractAaxlHandler.java:191)
	at org.osate.ui.handlers.AaxlReadOnlyHandlerAsJob$ActionAsJob.runInWorkspace(AaxlReadOnlyHandlerAsJob.java:124)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by jjhugues** [comment]
Trivial copy/paste error, patch is

-                                               EMV2PropertyAssociation Like = SevList.isEmpty() ? null : LikeList.get(0);
+                                               EMV2PropertyAssociation Like = LikeList.isEmpty() ? null : LikeList.get(0);
