### ISSUE TITLE
ProvisionException accessing OSATE update sites.

### ISSUE THREAD

**Issue by schwerdf** [osate/osate2#2353]
## Summary
When trying to access any of the OSATE update sites using either Eclipse or Maven's Tycho plugin, the following Java exception occurs. This is making it impossible to install any OSATE plugins or run any Maven builds depending on OSATE.

```
org.eclipse.equinox.p2.core.ProvisionException
Unable to read repository at https://osate-build.sei.cmu.edu/download/osate/stable/updates/content.xml.
Unable to read repository at https://osate-build.sei.cmu.edu/download/osate/stable/updates/content.xml.
sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

The corresponding stack trace from the workspace log is

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1000)
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:992)
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:988)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:380)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:285)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
	... 23 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:375)
	... 29 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sat Apr 11 18:59:59 CDT 2020
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:677)
	at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 34 more
```
* **OSATE Version**: Multiple
* **Operating System**: Windows 10, macOS

**Comment by lwrage** [comment]
OSATE update sites must include the version number (...stable/_2.7.1_/updates) or _testing_. It has always been like this.

**Comment by tuxji** [comment]
Our GitHub CI build just broke too.  We had been having no problems building a VERDICT plugin for OSATE until this morning when we started getting:

```
[INFO] Adding repository https://osate-build.sei.cmu.edu/download/osate/stable/2.6.1/updates
[ERROR] Failed to resolve target definition /home/runner/work/VERDICT/VERDICT/tools/verdict/com.ge.research.osate.verdict.target/com.ge.research.osate.verdict.target.target: Failed to load p2 metadata repository from location https://osate-build.sei.cmu.edu/download/osate/stable/2.6.1/updates: Unable to read repository at https://osate-build.sei.cmu.edu/download/osate/stable/2.6.1/updates/content.xml. sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed: NotAfter: Sat Apr 11 23:59:59 UTC 2020 -> [Help 1]
```

Our update site URL does include the version number.  The SSL certificate for osate-build.sei.cmu.edu is valid from 4/11/2018 to 4/11/2020, so it expired over a month ago.  I dunno if Maven applied a grace period that ran out or if something else broke, but I think this issue is real.

**Comment by schwerdf** [comment]
The specific version number was left out as this problem is occurring with _all_ the versions of OSATE we are referencing in Maven builds. Apologies for the confusion.

**Comment by lwrage** [comment]
OK, because of the wrong URL I didn't even look at the stack trace. Which certificate do you get when accessing the site in a browser? I get one with validity until October 26, SHA-256 fingerprint is
16:8B:A2:D8:FB:62:00:8D:A0:01:C7:5F:48:E0:CF:51:5A:F8:75:AB:2E:AA:90:D6:AD:5E:FD:64:6A:93:44:96

**Comment by yoogx** [comment]
From the command line I get an expired certificate

➜  ~ openssl s_client -showcerts -connect  osate-build.sei.cmu.edu:443
CONNECTED(00000005)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust ECC Certification Authority
verify return:1
depth=1 C = US, ST = MI, L = Ann Arbor, O = Internet2, OU = InCommon, CN = InCommon ECC Server CA
verify return:1
depth=0 C = US, postalCode = 15213, ST = PA, L = Pittsburgh, street = 4500 Fifth Ave, O = Carnegie Mellon University, OU = Software Engineering Institute, OU = Multi-Domain SSL, CN = osate-build.sei.cmu.edu
verify error:num=10:certificate has expired
notAfter=Apr 11 23:59:59 2020 GMT
verify return:1
depth=0 C = US, postalCode = 15213, ST = PA, L = Pittsburgh, street = 4500 Fifth Ave, O = Carnegie Mellon University, OU = Software Engineering Institute, OU = Multi-Domain SSL, CN = osate-build.sei.cmu.edu
notAfter=Apr 11 23:59:59 2020 GMT
verify return:1
---

**Comment by lwrage** [comment]
Nothing I can do, waiting for IT folks to fix this.

**Comment by lwrage** [comment]
The expired certificate has been removed, things should be back to normal.
