### ISSUE TITLE
Error propagation in feature group type result in errors.

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2#2408]
## Expected and Current Behavior
It should be possible to define an error propagation in a feature group type. This currently results in an error.

## Steps to Reproduce
1. Define an emv2 error propagation in a feature group type.
2. Errors regarding being unable to resolve the feature and the error are reported.

```aadl
package emv2_test
public
	feature group fgt
	features 
		ip1: in data port;
		
		annex emv2 {**
			use types ErrorLibrary;
			error propagations
				ip1: in propagation {ServiceError};
			end propagations;
		**};
	end fgt;	

end emv2_test;
```

**Comment by philip-alldredge** [comment]
For reference: E.4 (L1), (L3), (21), and (22). Page 69 in the official SAE PDF is the portions of the standard that reference feature group types having error propagations.

**Comment by joeseibel** [comment]
There are a few different problems here that need to be fixed. First of all, the validator throws a `ClassCastException` when a subclause exists in a feature group type, even if the subclause is empty. Here is the exception:
```
java.lang.ClassCastException: org.osate.aadl2.impl.FeatureGroupTypeImpl cannot be cast to org.osate.aadl2.ComponentClassifier
	at org.osate.xtext.aadl2.errormodel.validation.ErrorModelValidator.checkDuplicateSubclause(ErrorModelValidator.java:558)
	at org.osate.xtext.aadl2.errormodel.validation.ErrorModelValidator.caseErrorModelSubclause(ErrorModelValidator.java:296)
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:318)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:150)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:299)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:245)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:40)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:200)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:142)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:124)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:57)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:524)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:49)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Secondly, the scope provider does not resolve the references to `ip1` and `ServiceError`.

Thirdly, the validator throws another `ClassCastException` when an error propagation is in a feature group type:
```
java.lang.ClassCastException: org.osate.aadl2.impl.FeatureGroupTypeImpl cannot be cast to org.osate.aadl2.ComponentClassifier
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.getAssociatedClassifier(EMV2Util.java:203)
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.getAllContainingClassifierEMV2Subclauses(EMV2Util.java:176)
	at org.osate.xtext.aadl2.errormodel.util.EMV2Util.findErrorContainment(EMV2Util.java:381)
	at org.osate.xtext.aadl2.errormodel.validation.ErrorModelValidator.checkTypePropagationAndContainment(ErrorModelValidator.java:530)
	at org.osate.xtext.aadl2.errormodel.validation.ErrorModelValidator.caseErrorPropagation(ErrorModelValidator.java:209)
	at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:318)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:150)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:299)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:245)
	at org.eclipse.xtext.validation.CancelableDiagnostician.validate(CancelableDiagnostician.java:40)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:200)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:142)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:146)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:124)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:57)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:524)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:496)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:135)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:49)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
These stack traces show that the validator and `EMV2Util` assume that a subclause is always in a `ComponentClassifier`. There are probably lots and lots of places in EMV2 code that make this assumption.

**Comment by lwrage** [comment]
It is not clear if this construct really makes sense. See saeaadl/emv2#50.

**Comment by lwrage** [comment]
We don't support error model annex subclauses in feature group types any longer.
